rule Hijacked_Chrome_Extensions_2024_IPs_Domains
{
  meta:
    author      = "Tenbite @ https://x.com/BitOfTen"
    date        = "2025/01/03"
    description = "Hackers compromised developer accounts and inserted malicious code into 35+ Google Chrome extensions. This rule detects IPs and domains possibly associated with the campaign.Ref - https://www.extensiontotal.com/cyberhaven-incident-live "

  strings:
    // -- IP Addresses --
    $ip1  = "149.28.124.84"
    $ip2  = "45.76.225.148"
    $ip3  = "136.244.115.219"
    $ip4  = "149.248.44.88"
    $ip5  = "108.61.23.192"
    $ip6  = "80.240.21.36"
    $ip7  = "45.32.69.11"
    $ip8  = "155.138.253.165"
    $ip9  = "45.77.5.196"
    $ip10 = "144.202.123.86"
    $ip11 = "74.220.199.9"
    $ip12 = "45.32.231.212"
    $ip13 = "149.28.117.236"
    $ip14 = "137.220.48.214"
    $ip15 = "149.248.2.160"

    // -- C2 Domains --
    $domain1  = "cyberhavenext.pro"
    $domain2  = "gptforbusiness.site"
    $domain3  = "ext.businessforai.com"
    $domain4  = "barefootcontractor.com"
    $domain5  = "uvoice.live"
    $domain7  = "primusext.pro"
    $domain8  = "ultrablock.pro"
    $domain9  = "dearflip.pro"
    $domain10 = "parrottalks.info"
    $domain11 = "vidnozflex.live"
    $domain12 = "wakelet.ink"
    $domain13 = "locallyext.ink"
    $domain14 = "tinamind.info"
    $domain15 = "apple-ads-metric.com"
    $domain16 = "aeromexi.co"
    $domain17 = "gptforads.info"
    $domain18 = "blockforads.com"
    $domain19 = "ytbadblocker.com"
    $domain20 = "searchcopilot.co"
    $domain21 = "geminiaigg.pro"
    $domain22 = "blockadsonyt.vip"
    $domain23 = "fadblock.pro"
    $domain24 = "lltvmarkets.com"
    $domain25 = "savgptforchrome.pro"
    $domain26 = "bardaiforchrome.live"
    $domain27 = "com-freeapps.com"
    $domain28 = "gpt4summary.ink"
    $domain29 = "searchaiassitant.info"
    $domain30 = "artseasy.com"
    $domain31 = "savechatgpt.site"
    $domain32 = "upwordwave.com"
    $domain33 = "yescaptcha.pro"
    $domain34 = "videodownloadhelper.pro"
    $domain35 = "castorus.info"
    $domain36 = "bookmarkfc.info"
    $domain37 = "proxyswitchyomega.pro"
    $domain38 = "graphqlnetwork.pro"
    $domain39 = "iobit.pro"
    $domain40 = "internetdownloadmanager.pro"
    $domain41 = "searchgptchat.info"
    $domain42 = "pieadblock.pro"
    $domain43 = "gptdetector.live"
    $domain44 = "chatgptextent.pro"
    $domain45 = "youtubeadsblocker.live"
    $domain46 = "chatgptextension.site"
    $domain47 = "remiwantnun.com"
    $domain48 = "okta-onsolve.com"
    $domain49 = "capitalizerutc.com"
    $domain50 = "extensionpolicyprivacy.com"
    $domain51 = "policyextension.info"
    $domain52 = "extensionpolicy.net"
    $domain53 = "checkpolicy.site"
    $domain54 = "linewizeconnect.com"
    $domain55 = "extensionbuysell.com"
    $domain56 = "readermodeext.info"
    $domain57 = "adskiper.net"
    $domain58 = "aiforgemini.com"
    $domain59 = "sclpfybn.com"
    $domain60 = "tnagofsg.com"
    $domain61 = "kra18.com"

  condition:
    // Trigger if ANY of these extension IDs, IPs, or domains appear
	any of them
}

rule Hijacked_Chrome_Extensions_2024_Names_IDs
{
  meta:
    author      = "Tenbite @ https://x.com/BitOfTen"
    date        = "2025/01/03"
    description = "Hackers compromised developer accounts and inserted malicious code into 35+ Google Chrome extensions. This rule detects known extension NAMES possibly associated with the campaign. Ref - https://www.extensiontotal.com/cyberhaven-incident-live"

  strings:
    $name1  = "YesCaptcha assistant"
    $name2  = "Bookmark Favicon Changer"
    $name3  = "Proxy SwitchyOmega (V3)"
    $name4  = "GraphQL Network Inspector"
    $name5  = "AI Assistant"
    $name6  = "Bard AI chat"
    $name7  = "ChatGPT for Google Meet"
    $name8  = "Search Copilot AI Assistant for Chrome"
    $name9  = "TinaMind"
    $name10 = "Wayin AI"
    $name11 = "VPNCity"
    $name12 = "Internxt VPN"
    $name13 = "Vidnoz Flex"
    $name14 = "VidHelper"
    $name15 = "Castorus"
    $name16 = "Uvoice"
    $name17 = "Reader Mode"
    $name18 = "ParrotTalks"
    $name19 = "Primus"
    $name20 = "Keyboard History Recorder"
    $name21 = "ChatGPT Assistant"
    $name22 = "Visual Effects for Google Meet"
    $name23 = "AI Shop Buddy"
    $name24 = "Cyberhaven V3 Security Extension"
    $name25 = "Earny"
    $name26 = "Rewards Search Automator"
    $name27 = "Tackker"
    $name28 = "Sort By"
    $name29 = "Email Hunter"
    $name30 = "ChatGPT Quick Access"
    $name31 = "Where is Cookie?"
    $name32 = "Web Mirror"
    $name33 = "ChatGPT App"
    $name34 = "Hi AI"
    $name35 = "Web3Password Manager"
	
	// -- Extension IDs --
    $extId1  = "bibjgkidgpfbblifamdlkdlhgihmfohh"
    $extId2  = "pkgciiiancapdlpcbppfkmeaieppikkk"
    $extId3  = "epdjhgbipjpbbhoccdeipghoihibnfja"
    $extId4  = "bbdnohkpnbkdkmnkddobeafboooinpla"
    $extId5  = "befflofjcniongenjmbkgkoljhgliihe"
    $extId6  = "cedgndijpacnfbdggppddacngjfdkaca"
    $extId7  = "nnpnnpemnckcfdebeekibpiijlicmpom"
    $extId8  = "dpggmcodlahmljkhlmpgpdcffdaoccni"
    $extId9  = "cplhlgabfijoiabgkigdafklbhhdkahj"
    $extId10 = "egmennebgadmncfjafcemlecimkepcle"
    $extId11 = "acmfnomgphggonodopogfbmkneepfgnh"
    $extId12 = "mnhffkhmpnefgklngfmlndmkimimbphc"
    $extId13 = "oaikpkmjciadfpddlpjjdapglcihgdle"
    $extId14 = "fbmlcbhdmilaggedifpihjgkkmdgeljh"
    $extId15 = "kkodiihpgodmdankclfibbiphjkfdenh"
    $extId16 = "oeiomhmbaapihbilkfkhmlajkeegnjhe"
    $extId17 = "jiofmdifioeejeilfkpegipdjiopiekl"
    $extId18 = "hihblcmlaaademjlakdpicchbjnnnkbo"
    $extId19 = "ndlbedplllcgconngcnfmkadhokfaaln"
    $extId20 = "igbodamhgjohafcenbcljfegbipdfjpk"
    $extId21 = "bgejafhieobnfpjlpcjjggoboebonfcg"
    $extId22 = "llimhhconnjiflfimocjggfjdlmlhblm"
    $extId23 = "hodiladlefdpcbemnbbcpclbmknkiaem"
    $extId24 = "epikoohpebngmakjinphfiagogjcnddm"
    $extId25 = "pajkjnmeojmbapicmbpliphjmcekeaac"
    $extId26 = "ogbhbgkiojdollpjbhbamafmedkeockb"
    $extId27 = "eanofdhdfbcalhflpbdipkjjkoimeeod"
    $extId28 = "ekpkdmohpdnebfedjjfklhpefgpgaaji"
    $extId29 = "miglaibdlgminlepgeifekifakochlka"
    $extId30 = "mbindhfolmpijhodmgkloeeppmkhpmhc"
    $extId31 = "eaijffijbobmnonfhilihbejadplhddo"
    $extId32 = "lbneaaedflankmgmfbmaplggbmjjmbae"
    $extId33 = "hmiaoahjllhfgebflooeeefeiafpkfde"
    $extId34 = "pdkmmfdfggfpibdjbbghggcllhhainjo"
    $extId35 = "emedckhdnioeieppmeojgegjfkhdlaeo"
    $extId36 = "didhgeamncokiaegffipckhhcpnmlcbl"

  condition:
    any of them
}
