//! AI-YARA correlation engine for super-enhanced threat detection
//! Combines AI analysis with YARA rule matching and generates dynamic rules

use super::{CorrelationConfig, CorrelationInput, BehavioralIndicator, NetworkIndicator};
use crate::ai::{AIAnalyzer, AnalysisRequest, AnalysisResult, AnalysisType, AnalysisInput, ThreatClassification, Severity, Finding, AIError, AIResult};
use crate::detection::yara_engine::YaraEngine;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, SystemTime};
use serde::{Deserialize, Serialize};
use tracing::{info, warn, error, debug};
use tokio::sync::RwLock;

/// AI-YARA correlation engine
pub struct AIYaraCorrelator {
    /// Configuration
    config: CorrelationConfig,
    /// AI analyzer
    ai_analyzer: Option<Arc<dyn AIAnalyzer + Send + Sync>>,
    /// YARA engine
    yara_engine: Arc<YaraEngine>,
    /// Dynamic rules cache
    dynamic_rules: Arc<RwLock<HashMap<String, DynamicRule>>>,
    /// Correlation cache
    correlation_cache: Arc<RwLock<HashMap<String, CachedCorrelationResult>>>,
    /// Statistics
    stats: Arc<RwLock<CorrelationStats>>,
}

/// Dynamic YARA rule generated by AI
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DynamicRule {
    /// Rule identifier
    pub rule_id: String,
    /// Rule name
    pub rule_name: String,
    /// YARA rule content
    pub rule_content: String,
    /// Generation confidence
    pub confidence: f32,
    /// Creation timestamp
    pub created_at: SystemTime,
    /// Last used timestamp
    pub last_used: Option<SystemTime>,
    /// Usage count
    pub usage_count: u64,
    /// Associated threat family
    pub threat_family: Option<String>,
    /// Rule metadata
    pub metadata: HashMap<String, String>,
}

/// Cached correlation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CachedCorrelationResult {
    /// Correlation result
    pub result: CorrelationResult,
    /// Cache timestamp
    pub cached_at: SystemTime,
    /// Cache TTL
    pub ttl: Duration,
}

/// Comprehensive correlation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrelationResult {
    /// Overall threat score (0.0 to 1.0)
    pub threat_score: f32,
    /// Threat classification
    pub threat_classification: ThreatClassification,
    /// AI analysis result
    pub ai_result: Option<AnalysisResult>,
    /// YARA match results
    pub yara_matches: Vec<YaraMatch>,
    /// Dynamic rules generated
    pub generated_rules: Vec<DynamicRule>,
    /// Correlation confidence
    pub confidence: f32,
    /// Threat indicators
    pub threat_indicators: Vec<ThreatIndicator>,
    /// Behavioral correlation results
    pub behavioral_correlation: Option<BehavioralCorrelation>,
    /// Network correlation results
    pub network_correlation: Option<NetworkCorrelation>,
    /// Processing metadata
    pub metadata: CorrelationMetadata,
}

/// YARA match result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct YaraMatch {
    /// Rule name that matched
    pub rule_name: String,
    /// Match score
    pub score: f32,
    /// Matched strings
    pub matched_strings: Vec<MatchedString>,
    /// Rule metadata
    pub rule_metadata: HashMap<String, String>,
    /// Match confidence
    pub confidence: f32,
}

/// Matched string in YARA rule
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchedString {
    /// String identifier
    pub identifier: String,
    /// Matched content
    pub content: String,
    /// Offset in file
    pub offset: u64,
    /// Length of match
    pub length: usize,
}

/// Threat indicator from correlation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatIndicator {
    /// Indicator type
    pub indicator_type: IndicatorType,
    /// Indicator value
    pub value: String,
    /// Confidence score
    pub confidence: f32,
    /// Source of indicator (AI, YARA, etc.)
    pub source: String,
    /// Severity level
    pub severity: Severity,
    /// Description
    pub description: String,
}

/// Type of threat indicator
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum IndicatorType {
    /// File hash
    FileHash,
    /// IP address
    IpAddress,
    /// Domain name
    Domain,
    /// URL
    Url,
    /// Registry key
    RegistryKey,
    /// File path
    FilePath,
    /// Process name
    ProcessName,
    /// Mutex name
    Mutex,
    /// Network signature
    NetworkSignature,
    /// Behavioral pattern
    BehavioralPattern,
    /// Code pattern
    CodePattern,
    /// Custom indicator
    Custom(String),
}

/// Behavioral correlation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BehavioralCorrelation {
    /// Behavioral score
    pub score: f32,
    /// Detected behaviors
    pub behaviors: Vec<DetectedBehavior>,
    /// Behavioral patterns
    pub patterns: Vec<BehavioralPattern>,
    /// Anomaly score
    pub anomaly_score: f32,
}

/// Detected malicious behavior
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectedBehavior {
    /// Behavior type
    pub behavior_type: String,
    /// Confidence score
    pub confidence: f32,
    /// Description
    pub description: String,
    /// Evidence
    pub evidence: Vec<String>,
    /// Severity
    pub severity: Severity,
}

/// Behavioral pattern
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BehavioralPattern {
    /// Pattern name
    pub name: String,
    /// Pattern description
    pub description: String,
    /// Match confidence
    pub confidence: f32,
    /// Associated indicators
    pub indicators: Vec<String>,
}

/// Network correlation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkCorrelation {
    /// Network threat score
    pub score: f32,
    /// Suspicious connections
    pub suspicious_connections: Vec<SuspiciousConnection>,
    /// C2 indicators
    pub c2_indicators: Vec<C2Indicator>,
    /// Exfiltration indicators
    pub exfiltration_indicators: Vec<ExfiltrationIndicator>,
}

/// Suspicious network connection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuspiciousConnection {
    /// Remote address
    pub remote_address: String,
    /// Remote port
    pub remote_port: Option<u16>,
    /// Protocol
    pub protocol: String,
    /// Suspicion reason
    pub reason: String,
    /// Confidence score
    pub confidence: f32,
}

/// Command and control indicator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct C2Indicator {
    /// C2 server address
    pub server_address: String,
    /// Communication pattern
    pub pattern: String,
    /// Confidence score
    pub confidence: f32,
    /// Evidence
    pub evidence: Vec<String>,
}

/// Data exfiltration indicator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExfiltrationIndicator {
    /// Target address
    pub target_address: String,
    /// Data volume
    pub data_volume: u64,
    /// Exfiltration method
    pub method: String,
    /// Confidence score
    pub confidence: f32,
}

/// Correlation processing metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrelationMetadata {
    /// Processing start time
    pub start_time: SystemTime,
    /// Processing duration
    pub duration: Duration,
    /// AI analysis time
    pub ai_analysis_time: Option<Duration>,
    /// YARA analysis time
    pub yara_analysis_time: Option<Duration>,
    /// Rules generated count
    pub rules_generated: u32,
    /// Cache hit
    pub cache_hit: bool,
    /// Processing version
    pub version: String,
}

/// Correlation statistics
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CorrelationStats {
    /// Total correlations performed
    pub total_correlations: u64,
    /// Successful correlations
    pub successful_correlations: u64,
    /// Failed correlations
    pub failed_correlations: u64,
    /// Cache hits
    pub cache_hits: u64,
    /// Dynamic rules generated
    pub dynamic_rules_generated: u64,
    /// Average processing time
    pub avg_processing_time: Duration,
    /// Threat detection rate
    pub threat_detection_rate: f32,
    /// AI analysis success rate
    pub ai_success_rate: f32,
    /// YARA match rate
    pub yara_match_rate: f32,
}

impl AIYaraCorrelator {
    /// Create new AI-YARA correlator
    pub fn new(config: CorrelationConfig, yara_engine: Arc<YaraEngine>) -> Self {
        Self {
            config,
            ai_analyzer: None,
            yara_engine,
            dynamic_rules: Arc::new(RwLock::new(HashMap::new())),
            correlation_cache: Arc::new(RwLock::new(HashMap::new())),
            stats: Arc::new(RwLock::new(CorrelationStats::default())),
        }
    }

    /// Set AI analyzer
    pub fn set_ai_analyzer(&mut self, analyzer: Arc<dyn AIAnalyzer + Send + Sync>) {
        self.ai_analyzer = Some(analyzer);
    }

    /// Perform comprehensive correlation analysis
    pub async fn correlate(&self, input: CorrelationInput) -> Result<CorrelationResult, CorrelationError> {
        let start_time = SystemTime::now();
        
        info!("Starting AI-YARA correlation for file: {}", input.file_path);

        // Check cache first
        let cache_key = self.generate_cache_key(&input);
        if let Some(cached_result) = self.check_cache(&cache_key).await {
            info!("Returning cached correlation result");
            return Ok(cached_result);
        }

        // Initialize result
        let mut result = CorrelationResult {
            threat_score: 0.0,
            threat_classification: ThreatClassification {
                family: "Unknown".to_string(),
                variant: None,
                malware_type: vec!["Unknown".to_string()],
                attack_techniques: vec![],
                confidence: 0.0,
            },
            ai_result: None,
            yara_matches: Vec::new(),
            generated_rules: Vec::new(),
            confidence: 0.0,
            threat_indicators: Vec::new(),
            behavioral_correlation: None,
            network_correlation: None,
            metadata: CorrelationMetadata {
                start_time,
                duration: Duration::ZERO,
                ai_analysis_time: None,
                yara_analysis_time: None,
                rules_generated: 0,
                cache_hit: false,
                version: "1.0.0".to_string(),
            },
        };

        // Run AI analysis if available
        if let Some(ref ai_analyzer) = self.ai_analyzer {
            if self.config.enable_ai_correlation {
                match self.run_ai_analysis(ai_analyzer.clone(), &input).await {
                    Ok(ai_result) => {
                        result.ai_result = Some(ai_result);
                    }
                    Err(e) => {
                        warn!("AI analysis failed: {}", e);
                    }
                }
            }
        }

        // Run YARA analysis
        match self.run_yara_analysis(&input).await {
            Ok(yara_matches) => {
                result.yara_matches = yara_matches;
            }
            Err(e) => {
                warn!("YARA analysis failed: {}", e);
            }
        }

        // Generate dynamic rules if enabled
        if self.config.enable_dynamic_rules {
            if let Some(ref ai_result) = result.ai_result {
                if ai_result.confidence >= self.config.rule_generation_threshold {
                    match self.generate_dynamic_rules(ai_result, &input).await {
                        Ok(rules) => {
                            result.generated_rules = rules;
                            result.metadata.rules_generated = result.generated_rules.len() as u32;
                        }
                        Err(e) => {
                            warn!("Dynamic rule generation failed: {}", e);
                        }
                    }
                }
            }
        }

        // Perform behavioral correlation
        if self.config.enable_behavioral_correlation && !input.behavioral_indicators.is_empty() {
            result.behavioral_correlation = Some(self.correlate_behavioral_indicators(&input.behavioral_indicators).await);
        }

        // Perform network correlation
        if !input.network_indicators.is_empty() {
            result.network_correlation = Some(self.correlate_network_indicators(&input.network_indicators).await);
        }

        // Calculate final threat score and confidence
        self.calculate_final_scores(&mut result);

        // Extract threat indicators
        result.threat_indicators = self.extract_threat_indicators(&result);

        // Update metadata
        result.metadata.duration = start_time.elapsed().unwrap_or(Duration::ZERO);

        // Cache result
        self.cache_result(&cache_key, &result).await;

        // Update statistics
        self.update_stats(true, &result).await;

        info!("AI-YARA correlation completed in {:?}", result.metadata.duration);
        Ok(result)
    }

    /// Run AI analysis on input
    async fn run_ai_analysis(
        &self,
        ai_analyzer: Arc<dyn AIAnalyzer + Send + Sync>,
        _input: &CorrelationInput,
    ) -> AIResult<AnalysisResult> {
        let analysis_input = if let Some(ref content) = _input.file_content {
            AnalysisInput::BinaryData {
                data: content.clone(),
                filename: _input.file_path.clone(),
                file_type: "unknown".to_string(),
            }
        } else {
            AnalysisInput::TextData {
                content: format!("File: {}", _input.file_path),
                data_type: "file_path".to_string(),
            }
        };

        let request = AnalysisRequest {
            analysis_type: AnalysisType::MalwareClassification,
            input_data: analysis_input,
            model: None,
            context: HashMap::new(),
        };

        let start_time = SystemTime::now();
        let result = ai_analyzer.analyze(request).await?;
        let analysis_time = start_time.elapsed().unwrap_or(Duration::ZERO);

        debug!("AI analysis completed in {:?}", analysis_time);
        Ok(result)
    }

    /// Run YARA analysis on input
    async fn run_yara_analysis(&self, _input: &CorrelationInput) -> Result<Vec<YaraMatch>, CorrelationError> {
        let start_time = SystemTime::now();
        
        // For now, return empty matches as YARA integration would be complex
        // In a real implementation, this would use the YARA engine
        let matches = Vec::new();
        
        let analysis_time = start_time.elapsed().unwrap_or(Duration::ZERO);
        debug!("YARA analysis completed in {:?}", analysis_time);
        
        Ok(matches)
    }

    /// Generate dynamic YARA rules based on AI analysis
    async fn generate_dynamic_rules(
        &self,
        ai_result: &AnalysisResult,
        _input: &CorrelationInput,
    ) -> Result<Vec<DynamicRule>, CorrelationError> {
        let mut rules = Vec::new();

        // Generate rule based on AI findings
        if let Some(ref threat_classification) = ai_result.threat_classification {
            let rule_content = self.generate_rule_content(threat_classification, &ai_result.findings, _input);
            
            let rule = DynamicRule {
                rule_id: format!("ai_generated_{}", self.generate_uuid()),
                rule_name: format!("AI_Generated_{}", threat_classification.family),
                rule_content,
                confidence: ai_result.confidence,
                created_at: SystemTime::now(),
                last_used: None,
                usage_count: 0,
                threat_family: Some(threat_classification.family.clone()),
                metadata: HashMap::new(),
            };

            rules.push(rule);
        }

        // Store dynamic rules
        let mut dynamic_rules = self.dynamic_rules.write().await;
        for rule in &rules {
            dynamic_rules.insert(rule.rule_id.clone(), rule.clone());
        }

        // Cleanup old rules if limit exceeded
        if dynamic_rules.len() > self.config.max_dynamic_rules {
            self.cleanup_old_rules(&mut dynamic_rules).await;
        }

        Ok(rules)
    }

    /// Generate YARA rule content from AI analysis
    fn generate_rule_content(
        &self,
        threat_classification: &ThreatClassification,
        findings: &[Finding],
        _input: &CorrelationInput,
    ) -> String {
        let mut rule_content = format!(
            r#"rule AI_Generated_{}
{{
    meta:
        description = "AI-generated rule for {} malware"
        family = "{}"
        confidence = "AI-generated"
        
    strings:
"#,
            threat_classification.family.replace(" ", "_"),
            threat_classification.malware_type.join(", "),
            threat_classification.family
        );

        // Add string patterns based on findings
        for (i, finding) in findings.iter().enumerate() {
            if !finding.evidence.is_empty() {
                rule_content.push_str(&format!(
                    r#"        $evidence_{} = "{}"
"#,
                    i,
                    finding.evidence.join(" ")
                ));
            }
        }

        // Add condition
        rule_content.push_str(
            r#"        
    condition:
        any of them
}
"#,
        );

        rule_content
    }

    /// Generate a simple UUID-like string
    fn generate_uuid(&self) -> String {
        use std::time::{SystemTime, UNIX_EPOCH};
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        format!("{:x}", timestamp)
    }

    /// Cleanup old dynamic rules
    async fn cleanup_old_rules(&self, dynamic_rules: &mut HashMap<String, DynamicRule>) {
        // Remove least recently used rules
        let mut rules_vec: Vec<_> = dynamic_rules.values().collect();
        rules_vec.sort_by(|a, b| {
            let a_time = a.last_used.unwrap_or(a.created_at);
            let b_time = b.last_used.unwrap_or(b.created_at);
            a_time.cmp(&b_time)
        });

        // Remove oldest 10% of rules
        let remove_count = dynamic_rules.len() / 10;
        let rule_ids_to_remove: Vec<String> = rules_vec.iter()
            .take(remove_count)
            .map(|rule| rule.rule_id.clone())
            .collect();
        
        for rule_id in rule_ids_to_remove {
            dynamic_rules.remove(&rule_id);
        }
    }

    /// Correlate behavioral indicators
    async fn correlate_behavioral_indicators(&self, indicators: &[BehavioralIndicator]) -> BehavioralCorrelation {
        // Simplified behavioral correlation
        let score = indicators.len() as f32 * 0.1;
        
        BehavioralCorrelation {
            score: score.min(1.0),
            behaviors: Vec::new(),
            patterns: Vec::new(),
            anomaly_score: 0.0,
        }
    }

    /// Correlate network indicators
    async fn correlate_network_indicators(&self, indicators: &[NetworkIndicator]) -> NetworkCorrelation {
        // Simplified network correlation
        let score = indicators.len() as f32 * 0.15;
        
        NetworkCorrelation {
            score: score.min(1.0),
            suspicious_connections: Vec::new(),
            c2_indicators: Vec::new(),
            exfiltration_indicators: Vec::new(),
        }
    }

    /// Calculate final threat score and confidence
    fn calculate_final_scores(&self, result: &mut CorrelationResult) {
        let mut total_score = 0.0;
        let mut total_weight = 0.0;

        // AI score contribution
        if let Some(ref ai_result) = result.ai_result {
            if ai_result.confidence >= self.config.ai_confidence_threshold {
                total_score += ai_result.confidence * self.config.ai_weight;
                total_weight += self.config.ai_weight;
            }
        }

        // YARA score contribution
        if !result.yara_matches.is_empty() {
            let yara_score: f32 = result.yara_matches.iter()
                .map(|m| m.score)
                .sum::<f32>() / result.yara_matches.len() as f32;
            
            if yara_score >= self.config.yara_score_threshold {
                total_score += yara_score * self.config.yara_weight;
                total_weight += self.config.yara_weight;
            }
        }

        // Behavioral score contribution
        if let Some(ref behavioral) = result.behavioral_correlation {
            total_score += behavioral.score * 0.2;
            total_weight += 0.2;
        }

        // Network score contribution
        if let Some(ref network) = result.network_correlation {
            total_score += network.score * 0.2;
            total_weight += 0.2;
        }

        // Calculate final scores
        result.threat_score = if total_weight > 0.0 {
            total_score / total_weight
        } else {
            0.0
        };

        result.confidence = total_weight;
    }

    /// Extract threat indicators from correlation result
    fn extract_threat_indicators(&self, result: &CorrelationResult) -> Vec<ThreatIndicator> {
        let mut indicators = Vec::new();

        // Extract from AI analysis
        if let Some(ref ai_result) = result.ai_result {
            for finding in &ai_result.findings {
                indicators.push(ThreatIndicator {
                    indicator_type: IndicatorType::BehavioralPattern,
                    value: finding.description.clone(),
                    confidence: finding.confidence,
                    source: "AI".to_string(),
                    severity: finding.severity.clone(),
                    description: finding.description.clone(),
                });
            }
        }

        // Extract from YARA matches
        for yara_match in &result.yara_matches {
            indicators.push(ThreatIndicator {
                indicator_type: IndicatorType::CodePattern,
                value: yara_match.rule_name.clone(),
                confidence: yara_match.confidence,
                source: "YARA".to_string(),
                severity: Severity::Medium,
                description: format!("YARA rule match: {}", yara_match.rule_name),
            });
        }

        indicators
    }

    /// Generate cache key for correlation input
    fn generate_cache_key(&self, input: &CorrelationInput) -> String {
        format!("correlation_{}_{}", input.metadata.hash, input.file_path)
    }

    /// Check correlation cache
    async fn check_cache(&self, cache_key: &str) -> Option<CorrelationResult> {
        let cache = self.correlation_cache.read().await;
        if let Some(cached) = cache.get(cache_key) {
            let now = SystemTime::now();
            if now.duration_since(cached.cached_at).unwrap_or(Duration::MAX) < cached.ttl {
                let mut result = cached.result.clone();
                result.metadata.cache_hit = true;
                return Some(result);
            }
        }
        None
    }

    /// Cache correlation result
    async fn cache_result(&self, cache_key: &str, result: &CorrelationResult) {
        let cached_result = CachedCorrelationResult {
            result: result.clone(),
            cached_at: SystemTime::now(),
            ttl: Duration::from_secs(self.config.cache_ttl_seconds),
        };

        let mut cache = self.correlation_cache.write().await;
        cache.insert(cache_key.to_string(), cached_result);
    }

    /// Update correlation statistics
    async fn update_stats(&self, success: bool, result: &CorrelationResult) {
        let mut stats = self.stats.write().await;
        
        stats.total_correlations += 1;
        if success {
            stats.successful_correlations += 1;
        } else {
            stats.failed_correlations += 1;
        }

        if result.metadata.cache_hit {
            stats.cache_hits += 1;
        }

        stats.dynamic_rules_generated += result.metadata.rules_generated as u64;

        // Update averages
        let total_time = stats.avg_processing_time.as_millis() as u64 * (stats.total_correlations - 1);
        let new_time = result.metadata.duration.as_millis() as u64;
        stats.avg_processing_time = Duration::from_millis((total_time + new_time) / stats.total_correlations);

        // Update rates
        stats.threat_detection_rate = if result.threat_score > 0.5 { 
            (stats.threat_detection_rate * (stats.total_correlations - 1) as f32 + 1.0) / stats.total_correlations as f32
        } else {
            stats.threat_detection_rate * (stats.total_correlations - 1) as f32 / stats.total_correlations as f32
        };
    }

    /// Get correlation statistics
    pub async fn get_stats(&self) -> CorrelationStats {
        self.stats.read().await.clone()
    }

    /// Get dynamic rules count
    pub async fn get_dynamic_rules_count(&self) -> usize {
        self.dynamic_rules.read().await.len()
    }
}

/// Correlation error types
#[derive(Debug, thiserror::Error)]
pub enum CorrelationError {
    #[error("AI analysis error: {0}")]
    AIAnalysis(#[from] AIError),
    
    #[error("YARA analysis error: {0}")]
    YaraAnalysis(String),
    
    #[error("Rule generation error: {0}")]
    RuleGeneration(String),
    
    #[error("Configuration error: {0}")]
    Configuration(String),
    
    #[error("Cache error: {0}")]
    Cache(String),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::agent_config::AgentConfig;
    use crate::correlation::FileMetadata;
    use std::sync::Arc;

    #[test]
    fn test_correlator_creation() {
        let config = CorrelationConfig::default();
        let agent_config = Arc::new(AgentConfig::default());
        let yara_engine = Arc::new(YaraEngine::new(agent_config));
        let correlator = AIYaraCorrelator::new(config, yara_engine);
        
        assert!(correlator.ai_analyzer.is_none());
    }

    #[test]
    fn test_cache_key_generation() {
        let config = CorrelationConfig::default();
        let agent_config = Arc::new(AgentConfig::default());
        let yara_engine = Arc::new(YaraEngine::new(agent_config));
        let correlator = AIYaraCorrelator::new(config, yara_engine);
        
        let input = CorrelationInput {
            file_path: "/test/file.exe".to_string(),
            file_content: None,
            metadata: FileMetadata {
                size: 1024,
                hash: "abc123".to_string(),
                file_type: "exe".to_string(),
                created_at: None,
                modified_at: None,
                entropy: None,
                binary_metadata: None,
            },
            behavioral_indicators: Vec::new(),
            network_indicators: Vec::new(),
            process_info: None,
        };
        
        let cache_key = correlator.generate_cache_key(&input);
        assert!(cache_key.contains("abc123"));
        assert!(cache_key.contains("/test/file.exe"));
    }
}
